{{- if .Values.metrics.enabled }}
{{- if or .Values.controller.enabled .Values.webhook.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "twic.fullname" . }}-metrics-auth
  labels:
    {{- include "twic.labels" . | nindent 4 }}
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "twic.fullname" . }}-metrics-auth
  labels:
    {{- include "twic.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "twic.fullname" . }}-metrics-auth
subjects:
  {{- if .Values.controller.enabled }}
  - kind: ServiceAccount
    name: {{ include "twic.controllerServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.webhook.enabled }}
  - kind: ServiceAccount
    name: {{ include "twic.webhookServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "twic.fullname" . }}-metrics-reader
  labels:
    {{- include "twic.labels" . | nindent 4 }}
rules:
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
{{- with .Values.metrics.prometheusServiceAccount }}
{{- if and .name .namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "twic.fullname" $ }}-prometheus-metrics-reader
  labels:
    {{- include "twic.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "twic.fullname" $ }}-metrics-reader
subjects:
  - kind: ServiceAccount
    name: {{ .name | quote }}
    namespace: {{ .namespace | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
