{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "twic.fullname" . }}
  labels:
    {{- include "twic.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "twic.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8081
        {{- if .Values.metrics.enabled }}
        - protocol: TCP
          port: {{ .Values.metrics.servicePort }}
        {{- end }}
        {{- if .Values.webhook.enabled }}
        - protocol: TCP
          port: {{ .Values.webhook.port }}
        {{- end }}
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 443
{{- end }}
