{{- if and .Values.webhook.enabled (gt (int .Values.webhook.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "twic.fullname" . }}-webhook
  labels:
    {{- include "twic.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  minAvailable: {{ .Values.webhook.minAvailable }}
  selector:
    matchLabels:
      {{- include "twic.webhookSelectorLabels" . | nindent 6 }}
{{- end }}
