{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "twic.fullname" . }}
  labels:
    {{- include "twic.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.minAvailable }}
  selector:
    matchLabels:
      {{- include "twic.selectorLabels" . | nindent 6 }}
{{- end }}
