{{- if .Values.enableServiceMonitor }}
{{- if not .Values.metrics.enabled }}
{{- fail "enableServiceMonitor requires metrics.enabled to be true" }}
{{- end }}
{{- if not (or .Values.controller.enabled .Values.webhook.enabled) }}
{{- fail "enableServiceMonitor requires controller.enabled and/or webhook.enabled" }}
{{- end }}
{{- $m := .Values.metrics }}
{{- if .Values.controller.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "twic.fullname" . }}-controller-metrics
  labels:
    {{- include "twic.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  ports:
    - name: https
      port: {{ $m.servicePort }}
      targetPort: https
  selector:
    {{- include "twic.controllerSelectorLabels" . | nindent 4 }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "twic.fullname" . }}-controller
  labels:
    {{- include "twic.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- with $m.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "twic.controllerSelectorLabels" . | nindent 6 }}
  endpoints:
    - port: https
      path: /metrics
      interval: {{ $m.serviceMonitor.interval }}
      {{- if $m.secure }}
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: {{ $m.serviceMonitor.tlsInsecureSkipVerify }}
      {{- end }}
{{- end }}
{{- if .Values.webhook.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "twic.fullname" . }}-webhook-metrics
  labels:
    {{- include "twic.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  type: ClusterIP
  ports:
    - name: https
      port: {{ $m.servicePort }}
      targetPort: https
  selector:
    {{- include "twic.webhookSelectorLabels" . | nindent 4 }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "twic.fullname" . }}-webhook
  labels:
    {{- include "twic.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
    {{- with $m.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "twic.webhookSelectorLabels" . | nindent 6 }}
  endpoints:
    - port: https
      path: /metrics
      interval: {{ $m.serviceMonitor.interval }}
      {{- if $m.secure }}
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: {{ $m.serviceMonitor.tlsInsecureSkipVerify }}
      {{- end }}
{{- end }}
{{- end }}
